services:
  - type: web
    name: memorias-backend
    runtime: python
    repo: https://github.com/Mayza414/memorias-com-amor
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: memorias-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30
      - key: MAX_FILE_SIZE_MB
        value: 20
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: ALLOWED_ORIGINS
        value: https://seu-frontend.vercel.app,http://localhost:3000

  - type: postgresql
    name: memorias-db
    plan: free
    region: oregon
